name: Bazel Linux

on:
  workflow_dispatch:

jobs:
  # Building using the github runner environement directly.
  bazel:
    runs-on: ubuntu-latest
    env:
      CC:  gcc-10
      CXX: g++-10
    services:
      # Label used to access the service container
      bazel-remote-cache:
        # Docker Hub image
        image: buchgr/bazel-remote-cache
        env:
          BAZEL_REMOTE_S3_AUTH_METHOD: access_key
          BAZEL_REMOTE_S3_BUCKET: ${{secrets.AWS_BAZEL_CACHE_S3_BUCKET}}
          BAZEL_REMOTE_S3_ACCESS_KEY_ID: ${{secrets.AWS_BAZEL_CACHE_ACCESS_KEY}}
          BAZEL_REMOTE_S3_SECRET_ACCESS_KEY: ${{secrets.AWS_BAZEL_CACHE_SECRET_KEY}}
          BAZEL_REMOTE_S3_REGION: us-east-2
          BAZEL_REMOTE_ACCESS_LOG_LEVEL: all
          BAZEL_REMOTE_S3_ENDPOINT: s3.us-east-2.amazonaws.com
          BAZEL_REMOTE_DIR: /data
        ports:
          # Maps tcp port  on service container to the host
          - 9092:9092
          - 8080:8080
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Install Bazel
        run: |
          curl -fsSL https://bazel.build/bazel-release.pub.gpg | gpg --dearmor > bazel.gpg
          sudo mv bazel.gpg /etc/apt/trusted.gpg.d/
          echo "deb [arch=amd64] https://storage.googleapis.com/bazel-apt stable jdk1.8" | sudo tee /etc/apt/sources.list.d/bazel.list
          sudo apt-get update
          sudo apt-get install bazel
          bazel --version
      - name: Build
        run: bazel --output_base=/tmp/bazel-linux/output build --cxxopt=-std=c++20  --remote_cache=http://localhost:8080 //ortools/... //examples/...
      - name: Inspect
        run: |
          tree -fR /home/runner/.cache/bazel
          tree -fR /tmp/bazel-linux/output

