name: Bazel MacOS

on:
  workflow_dispatch:

jobs:
  bazel:
    runs-on: macos-latest
          
    steps:
      - uses: docker-practice/actions-setup-docker@master
        if: ${{ matrix.os == 'macos-latest' }}
      
      - name: Run Bazel Cache server
        uses: addnab/docker-run-action@v3
         with:
          image: buchgr/bazel-remote-cache
          options: |
            -e BAZEL_REMOTE_S3_AUTH_METHOD: access_key
            -e BAZEL_REMOTE_S3_BUCKET: ${{secrets.AWS_BAZEL_CACHE_S3_BUCKET}}
            -e BAZEL_REMOTE_S3_ACCESS_KEY_ID: ${{secrets.AWS_BAZEL_CACHE_ACCESS_KEY}}
            -e BAZEL_REMOTE_S3_SECRET_ACCESS_KEY: ${{secrets.AWS_BAZEL_CACHE_SECRET_KEY}}
            -e BAZEL_REMOTE_S3_REGION: us-east-2
            -e BAZEL_REMOTE_ACCESS_LOG_LEVEL: all
            -e BAZEL_REMOTE_S3_ENDPOINT: s3.us-east-2.amazonaws.com
            -e BAZEL_REMOTE_DIR: /data
            -p 9092:9092
            -p 8080:8080
        
      - name: Check out repository code
        uses: actions/checkout@v2
        
      - name: Install Bazel
        run: |
          brew update
          #brew install bazel
          bazel --version

      - name: Build
        run: bazel build --cxxopt=-std=c++20 --remote_cache=http://localhost:8080 //ortools/... //examples/...
