name: Bazel Docker

on: 
  workflow_dispatch:

jobs:
  Distros:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.allow_failure }}
    strategy:
      fail-fast: false
      matrix:
        distro: [alpine, centos, ubuntu]
        allow_failure: [false]
    env:
      DISTRO: ${{ matrix.distro }}
    steps:
    - uses: actions/checkout@v2
    - name: Build project
      run: make --directory=bazel ${DISTRO}_build