name: Bazel MacOS

on:
  workflow_dispatch:

jobs:
  bazel:
    runs-on: macos-latest
    services:
      # Label used to access the service container
      bazel-remote-cache:
        # Docker Hub image
        image: buchgr/bazel-remote-cache
        env:
          BAZEL_REMOTE_S3_AUTH_METHOD: access_key
          BAZEL_REMOTE_S3_BUCKET: ${{secrets.AWS_BAZEL_CACHE_S3_BUCKET}}
          BAZEL_REMOTE_S3_ACCESS_KEY_ID: ${{secrets.AWS_BAZEL_CACHE_ACCESS_KEY}}
          BAZEL_REMOTE_S3_SECRET_ACCESS_KEY: ${{secrets.AWS_BAZEL_CACHE_SECRET_KEY}}
          BAZEL_REMOTE_S3_REGION: us-east-2
          BAZEL_REMOTE_ACCESS_LOG_LEVEL: all
          BAZEL_REMOTE_DIR: /data
        ports:
          # Maps tcp port  on service container to the host
          - 9092:9092
          - 8080:8080
        volumes:
          - ~/.cache/bazel:/data
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install Bazel
        run: |
          brew update
          #brew install bazel
          bazel --version
      - name: Build
        run: bazel build --cxxopt=-std=c++20 --remote_cache=http://localhost:8080 //ortools/... //examples/...
