name: Bazel MacOS

on:
  workflow_dispatch:

jobs:
  bazel:
    runs-on: macos-latest
          
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      # https://github.com/envoyproxy/envoy/blob/main/bazel/README.md#quick-start-bazel-build-for-developers
      - name: install common deps
        run: | 
          brew install coreutils automake ninja clang-format
          
      # - name: install full xcode
      #   run: |
      #     sudo rm -rf /Library/Developer/CommandLineTools
      #     softwareupdate --all --install --force
      #     sudo xcode-select --install

      - name: Configure Homebrew cache
        uses: actions/cache@v2
        id: cache-brew
        with:
          path: |
            ~/Library/Caches/Homebrew/docker--*
            ~/Library/Caches/Homebrew/downloads/*--docker-*
          key: brew-${{ hashFiles('.github/brew-formulae') }}
          restore-keys: brew-

      # https://github.com/actions/runner/issues/1456#issue-1042407558
      - name: install and launch docker
        if: steps.cache-brew.outputs.cache-hit != 'true'
        run: |
          HOMEBREW_NO_AUTO_UPDATE=1 brew install --cask docker
          sudo /Applications/Docker.app/Contents/MacOS/Docker --unattended --install-privileged-components
          open -a /Applications/Docker.app --args --unattended --accept-license
          echo "We are waiting for Docker to be up and running. It can take over 2 minutes..."
          while ! /Applications/Docker.app/Contents/Resources/bin/docker info &>/dev/null; do sleep 1; done
      
      - name: Run Bazel Cache server
        run: |
          docker run \
            -e BAZEL_REMOTE_S3_AUTH_METHOD=access_key \
            -e BAZEL_REMOTE_S3_BUCKET=${{secrets.AWS_BAZEL_CACHE_S3_BUCKET}} \
            -e BAZEL_REMOTE_S3_ACCESS_KEY_ID=${{secrets.AWS_BAZEL_CACHE_ACCESS_KEY}} \
            -e BAZEL_REMOTE_S3_SECRET_ACCESS_KEY=${{secrets.AWS_BAZEL_CACHE_SECRET_KEY}} \
            -e BAZEL_REMOTE_S3_REGION=us-east-2 \
            -e BAZEL_REMOTE_ACCESS_LOG_LEVEL=all \
            -e BAZEL_REMOTE_S3_ENDPOINT=s3.us-east-2.amazonaws.com \
            -e BAZEL_REMOTE_DIR=/data \
            -e BAZEL_REMOTE_S3_PREFIX=ortools/macos-latest \
            -p 9092:9092 \
            -p 8080:8080 \
            buchgr/bazel-remote-cache

      - name: Inspect
        run: |
          curl localhost:8080/status

      - name: Build
        run: bazel build --cxxopt=-std=c++20 --remote_cache=http://localhost:8080 //ortools/... //examples/...
